'use strict';

(function() {

    class weekViewController {

        constructor($http, $scope, socket, $rootScope) {
            this.$http = $http;
            this.awesomeEvents = [];

            this.calendar;
            this.url = window.location;
            this.user;
            this.$scope = $scope;
            this.$scope.slot = this.calendar;
            $scope.events = [];
            
           
            //get calendar id from user ----------------------------
            paramSerializer: '$httpParamSerializerJQLike';

            if (!$rootScope.userIDglobal) {
                console.log("do nothing");
                //  window.location = window.location + "/" +  $rootScope.userIDglobal;
            } else {
                //  $rootScope.userIDglobal  = this.userIDtemp ;
            }

            //send request to BE to get user and then call method to get calendar------------------------------------
            $http.get('/api/users/' + $rootScope.userIDglobal).then(response => {
                this.user = response.data;
                this.getCalendar();
                socket.syncUpdates('calendar', this.calendar);
            });

            //autogenerated code --------------------------------------
            $scope.$on('$destroy', function() {
                socket.unsyncUpdates('calendar');
            });
        }

        //send request to BE to get calendar details -------------------------------
        getCalendar() {
            this.$http.get('/api/calendars/' + this.user.calID).then(response => {
                this.calendar = response.data;
                this.weekEvents();
            });
        }


        weekEvents() {

            this.$scope.calendarView = "week";
            this.$scope.calendarDate = new Date();


        }
    }
    //     } // End The for loop
    // } // End dayEvents method


    // }

    angular.module('takeTurnsApp')
        .controller('weekViewController', weekViewController);

})();
