'use strict';

(function() {

class weekViewController {

  constructor($http, $scope, socket, $rootScope) {
    this.$http = $http;
    this.calendar;
    this.memCounter;

   //get calendar id from user ----------------------------
  paramSerializer: '$httpParamSerializerJQLike';

if (!$rootScope.userIDglobal){
  console.log("do nothing" );
 //  window.location = window.location + "/" +  $rootScope.userIDglobal;
}else{
    //  $rootScope.userIDglobal  = this.userIDtemp ;
}

//send request to BE to get user and then call method to get calendar------------------------------------
    $http.get('/api/users/'+ $rootScope.userIDglobal).then(response => {
      this.user = response.data;
      this.getCalendar();
      socket.syncUpdates('calendar', this.calendar);
    });

//autogenerated code --------------------------------------
    $scope.$on('$destroy', function() {
      socket.unsyncUpdates('calendar');
    });
  }

//send request to BE to get calendar details -------------------------------
  getCalendar(){
   this.$http.get('/api/calendars/'+ this.user.calID).then(response => {
      this.calendar = response.data;
    });
  }





  addEvent() {
    if (this.newEvent) {
      this.$http.post('/api/events', { name: this.newEvent });
      this.newEvent = '';
    }
  }

  deleteEvents(event) {
    this.$http.delete('/api/events/' + event._id);
  }
}

angular.module('takeTurnsApp')
  .controller('weekViewController', weekViewController);

})();
