
'use strict';

(function() {

    class EmailSenderCtrl {

        constructor($http, $scope, socket, $cookies, emailDataContainer) {
            this.$http = $http;
            this.emailDataContainer = emailDataContainer;
            this.to;
            this.subject = this.emailDataContainer.getSubject();
            this.emailBody = this.emailDataContainer.getBody();
            this.result;
            this.message;
            //TODO set the who from as the name of the calendar not the name of the app as we have currently

            //after reading from this service clear all values
            this.emailDataContainer.clearAll();

//this one line of code below is jsut for testing the service for transfering data between controllers
console.log("22222222222222222 " + this.emailDataContainer.getBody());


// //get calendar id from user ----------------------------
//   paramSerializer: '$httpParamSerializerJQLike';
// if (!this.userIDtemp){
//   console.log("do nothing" );
//   window.location = window.location + "/" +  $rootScope.userIDglobal;
// }else{
//       $rootScope.userIDglobal  = this.userIDtemp ;
//       console.log("$rootScope.userIDglobal 555 = " + $rootScope.userIDglobal);
// }
           
//             //get calendar id from user ----------------------------
//             paramSerializer: '$httpParamSerializerJQLike';

//             //autogenerated code --------------------------------------
//             $scope.$on('$destroy', function() {
//                 socket.unsyncUpdates('calendar');
//             });
//         }
        }
        //send request to BE to send email -------------------------------this is working
        sendEmail() {


        	this.message="Sending E-mail...Please wait";
        	console.log("-------- in click send -----------");
        	console.log("-------- this.to -----------" + this.to);
        	console.log("-------- this.emailBody -----------" + this.emailBody);
        	console.log("-------- this.subject -----------" + this.subject);

            

            this.$http.post('/api/emails', {to: this.to, emailBody: this.emailBody, subject: this.subject}).then(response => {

                this.result = response.data;
                console.log("-------- request was sent and succeeded-----------");
                if(this.result == "sent") {
                    window.alert("Message Sent");
                    window.close();
                }
            });
        }
    }

    angular.module('takeTurnsApp')
        .controller('EmailSenderCtrl', EmailSenderCtrl);

})();
