'use strict';

(function() {

class EventCreatorController {

  constructor($http, $scope, socket,  $rootScope) {
    this.$http = $http;
    this.awesomeCalendars = [];
    this.calendar;
    this.userIDtemp ;
    this.user ;
    this.eventID ;



//get calendar id from user ----------------------------
  paramSerializer: '$httpParamSerializerJQLike';

if (!$rootScope.userIDglobal){
  console.log("do nothing" );
 //  window.location = window.location + "/" +  $rootScope.userIDglobal;
}else{
    //  $rootScope.userIDglobal  = this.userIDtemp ;
}

//send request to BE to get user and then call method to get calendar------------------------------------
    $http.get('/api/users/'+ $rootScope.userIDglobal).then(response => {
      this.user = response.data;
      this.getCalendar();
      socket.syncUpdates('calendar', this.calendar);
    });

//autogenerated code --------------------------------------
    $scope.$on('$destroy', function() {
      socket.unsyncUpdates('calendar');
    });
  }

//send request to BE to get calendar details -------------------------------
  getCalendar(){
   this.$http.get('/api/calendars/'+ this.user.calID).then(response => {
      this.calendar = response.data;
    });
  }


//send request to create new event - code is not working yet ------------------------------------------
  addEvent() {
    if (this.newEvent) {
      this.$http.post('/api/events', { name: this.newEvent });
      this.newEvent = '';
    }
    }
  

//send request to delete an event --- temporarily here for testing etc...
  deleteEvent(event) {
  this.eventID = event._id;
    this.$http.patch('/api/calendars/' + this.calendar._id +"/deleteEvent/"+ this.eventID).then(response => {
      this.calendar = response.data;
    });
}

}

angular.module('takeTurnsApp')
  .controller('EventCreatorController', EventCreatorController);

})();
